{% set name = "xorg-libSM" %}
{% set version = "1.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.x.org/releases/individual/lib/{{ name.split('-')[1] }}-{{ version }}.tar.xz
  sha256: be7c0abdb15cbfd29ac62573c1c82e877f9d4047ad15321e7ea97d1e43d835be

build:
  number: 1
  # xorg-libxdmcp, libxcb, libx11, libice aren't available on Windows because their dependencies clash with m2/msys2 and mingw64/ucrt64 toolchains.
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name|lower) }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - pkg-config
    - gnuconfig
    - make
    - autoconf
    - automake
    - gettext
    - libtool
  host:
    - libuuid {{ libuuid }}                    # [linux]
    - xorg-util-macros ==1.20.2
    - xorg-xorgproto {{ xorg_xorgproto }}
    - xorg-xtrans ==1.6.0
    - xorg-libice {{ xorg_libice }}

test:
  commands:
    - test -f $PREFIX/lib/libSM.dylib  # [osx]
    - test -f $PREFIX/lib/libSM.so     # [linux]

about:
  home: https://www.x.org/
  dev_url: https://gitlab.freedesktop.org/xorg/lib/libsm
  doc_url: https://gitlab.freedesktop.org/xorg/lib/libsm
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: The X.org core session management library.
  description: |
    The X.org core session management library.

extra:
  recipe-maintainers:
    - pkgw
